language: julia
os:
    - linux
julia:
    - 0.4
sudo: false
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.test("NetflixPrize", coverage=true)'
after_success:
    - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("NetflixPrize")); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'

